#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-asm
Version  : 6.1.1
Release  : 18
URL      : https://repo1.maven.org/maven2/org/ow2/asm/asm/6.1.1/asm-6.1.1.jar
Source0  : https://repo1.maven.org/maven2/org/ow2/asm/asm/6.1.1/asm-6.1.1.jar
Source1  : https://repo.maven.apache.org/maven2/asm/asm-parent/3.1/asm-parent-3.1.pom
Source2  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/4.1/asm-analysis-4.1.jar
Source3  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/4.1/asm-analysis-4.1.pom
Source4  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar
Source5  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.pom
Source6  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/6.2/asm-analysis-6.2.pom
Source7  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/7.0/asm-analysis-7.0.jar
Source8  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/7.0/asm-analysis-7.0.pom
Source9  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.jar
Source10  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.pom
Source11  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.pom
Source12  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.jar
Source13  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.pom
Source14  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.jar
Source15  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.pom
Source16  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-debug-all/6.0_ALPHA/asm-debug-all-6.0_ALPHA.jar
Source17  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-debug-all/6.0_ALPHA/asm-debug-all-6.0_ALPHA.pom
Source18  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-parent/4.1/asm-parent-4.1.pom
Source19  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-parent/4.2/asm-parent-4.2.pom
Source20  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-parent/5.0.1/asm-parent-5.0.1.pom
Source21  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-parent/5.0.4/asm-parent-5.0.4.pom
Source22  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-parent/6.0_ALPHA/asm-parent-6.0_ALPHA.pom
Source23  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/4.1/asm-tree-4.1.jar
Source24  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/4.1/asm-tree-4.1.pom
Source25  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.pom
Source26  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.jar
Source27  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.pom
Source28  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/4.1/asm-util-4.1.jar
Source29  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/4.1/asm-util-4.1.pom
Source30  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar
Source31  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.pom
Source32  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/5.1/asm-util-5.1.jar
Source33  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/5.1/asm-util-5.1.pom
Source34  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.2/asm-util-6.2.jar
Source35  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.2/asm-util-6.2.pom
Source36  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom
Source37  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar
Source38  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm/5.0.4/asm-5.0.4.pom
Source39  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm/5.1/asm-5.1.jar
Source40  : https://repo.maven.apache.org/maven2/org/ow2/asm/asm/5.1/asm-5.1.pom
Source41  : https://repo1.maven.org/maven2/asm/asm-commons/3.3.1/asm-commons-3.3.1.jar
Source42  : https://repo1.maven.org/maven2/asm/asm-commons/3.3.1/asm-commons-3.3.1.pom
Source43  : https://repo1.maven.org/maven2/asm/asm-parent/3.3.1/asm-parent-3.3.1.pom
Source44  : https://repo1.maven.org/maven2/asm/asm-tree/3.3.1/asm-tree-3.3.1.jar
Source45  : https://repo1.maven.org/maven2/asm/asm-tree/3.3.1/asm-tree-3.3.1.pom
Source46  : https://repo1.maven.org/maven2/asm/asm/3.1/asm-3.1.jar
Source47  : https://repo1.maven.org/maven2/asm/asm/3.1/asm-3.1.pom
Source48  : https://repo1.maven.org/maven2/asm/asm/3.3.1/asm-3.3.1.jar
Source49  : https://repo1.maven.org/maven2/asm/asm/3.3.1/asm-3.3.1.pom
Source50  : https://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
Source51  : https://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.pom
Source52  : https://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.1/asm-all-5.1.jar
Source53  : https://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.1/asm-all-5.1.pom
Source54  : https://repo1.maven.org/maven2/org/ow2/asm/asm-analysis/7.0-beta/asm-analysis-7.0-beta.pom
Source55  : https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.2/asm-commons-5.0.2.jar
Source56  : https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.2/asm-commons-5.0.2.pom
Source57  : https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4.jar
Source58  : https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4.pom
Source59  : https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/7.0-beta/asm-commons-7.0-beta.pom
Source60  : https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.0.2/asm-parent-5.0.2.pom
Source61  : https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3.pom
Source62  : https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.1/asm-parent-5.1.pom
Source63  : https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/6.0_BETA/asm-parent-6.0_BETA.pom
Source64  : https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.2/asm-tree-5.0.2.jar
Source65  : https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.2/asm-tree-5.0.2.pom
Source66  : https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.1/asm-tree-5.1.jar
Source67  : https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.1/asm-tree-5.1.pom
Source68  : https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/7.0-beta/asm-tree-7.0-beta.pom
Source69  : https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.jar
Source70  : https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.pom
Source71  : https://repo1.maven.org/maven2/org/ow2/asm/asm-util/7.0-beta/asm-util-7.0-beta.jar
Source72  : https://repo1.maven.org/maven2/org/ow2/asm/asm-util/7.0-beta/asm-util-7.0-beta.pom
Source73  : https://repo1.maven.org/maven2/org/ow2/asm/asm/4.1/asm-4.1.jar
Source74  : https://repo1.maven.org/maven2/org/ow2/asm/asm/4.1/asm-4.1.pom
Source75  : https://repo1.maven.org/maven2/org/ow2/asm/asm/4.2/asm-4.2.jar
Source76  : https://repo1.maven.org/maven2/org/ow2/asm/asm/4.2/asm-4.2.pom
Source77  : https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.2/asm-5.0.2.jar
Source78  : https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.2/asm-5.0.2.pom
Source79  : https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar
Source80  : https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom
Source81  : https://repo1.maven.org/maven2/org/ow2/asm/asm/6.0_BETA/asm-6.0_BETA.jar
Source82  : https://repo1.maven.org/maven2/org/ow2/asm/asm/6.0_BETA/asm-6.0_BETA.pom
Source83  : https://repo1.maven.org/maven2/org/ow2/asm/asm/6.1.1/asm-6.1.1.pom
Source84  : https://repo1.maven.org/maven2/org/ow2/asm/asm/6.2/asm-6.2.jar
Source85  : https://repo1.maven.org/maven2/org/ow2/asm/asm/6.2/asm-6.2.pom
Source86  : https://repo1.maven.org/maven2/org/ow2/asm/asm/7.0-beta/asm-7.0-beta.pom
Source87  : https://repo1.maven.org/maven2/org/ow2/asm/asm/7.0/asm-7.0.jar
Source88  : https://repo1.maven.org/maven2/org/ow2/asm/asm/7.0/asm-7.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-asm-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-asm package.
Group: Data

%description data
data components for the mvn-asm package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.1.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.1.1/asm-6.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm-parent/3.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/asm/asm-parent/3.1/asm-parent-3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/4.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/4.1/asm-analysis-4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/4.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/4.1/asm-analysis-4.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/5.0.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/5.0.3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/6.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/6.2/asm-analysis-6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/7.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/7.0/asm-analysis-7.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/7.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/7.0/asm-analysis-7.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.1
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.1
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/6.2
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/7.0
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/7.0
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/5.0.1
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/5.0.1
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/6.0_ALPHA
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/6.0_ALPHA/asm-debug-all-6.0_ALPHA.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/6.0_ALPHA
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/6.0_ALPHA/asm-debug-all-6.0_ALPHA.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/4.1
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/4.1/asm-parent-4.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/4.2
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/4.2/asm-parent-4.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.1
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.1/asm-parent-5.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.4
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.4/asm-parent-5.0.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/6.0_ALPHA
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/6.0_ALPHA/asm-parent-6.0_ALPHA.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/4.1
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/4.1/asm-tree-4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/4.1
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/4.1/asm-tree-4.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/6.2
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/4.1
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/4.1/asm-util-4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/4.1
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/4.1/asm-util-4.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.0.3
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.0.3
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.1
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.1/asm-util-5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.1
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.1/asm-util-5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/6.2
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/6.2/asm-util-6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/6.2
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/6.2/asm-util-6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.3
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.4
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.4
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.1
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.1/asm-5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.1
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.1/asm-5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm-commons/3.3.1
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/asm/asm-commons/3.3.1/asm-commons-3.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm-commons/3.3.1
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/asm/asm-commons/3.3.1/asm-commons-3.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm-parent/3.3.1
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/asm/asm-parent/3.3.1/asm-parent-3.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm-tree/3.3.1
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/asm/asm-tree/3.3.1/asm-tree-3.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm-tree/3.3.1
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/asm/asm-tree/3.3.1/asm-tree-3.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm/3.1
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/asm/asm/3.1/asm-3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm/3.1
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/asm/asm/3.1/asm-3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm/3.3.1
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/asm/asm/3.3.1
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/asm/asm/3.3.1/asm-3.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.0.3
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.0.3
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.1
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.1/asm-all-5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.1
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.1/asm-all-5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/7.0-beta
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/7.0-beta/asm-analysis-7.0-beta.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.2
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.2/asm-commons-5.0.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.2
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.2/asm-commons-5.0.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.4
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.4
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/7.0-beta
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/7.0-beta/asm-commons-7.0-beta.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.2
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.2/asm-parent-5.0.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.3
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.1
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.1/asm-parent-5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/6.0_BETA
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/6.0_BETA/asm-parent-6.0_BETA.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.0.2
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.0.2/asm-tree-5.0.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.0.2
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.0.2/asm-tree-5.0.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.1
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.1/asm-tree-5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.1
cp %{SOURCE67} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.1/asm-tree-5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0-beta
cp %{SOURCE68} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0-beta/asm-tree-7.0-beta.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0
cp %{SOURCE69} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0
cp %{SOURCE70} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/7.0-beta
cp %{SOURCE71} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/7.0-beta/asm-util-7.0-beta.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/7.0-beta
cp %{SOURCE72} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm-util/7.0-beta/asm-util-7.0-beta.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/4.1
cp %{SOURCE73} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/4.1/asm-4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/4.1
cp %{SOURCE74} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/4.1/asm-4.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/4.2
cp %{SOURCE75} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/4.2/asm-4.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/4.2
cp %{SOURCE76} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/4.2/asm-4.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.2
cp %{SOURCE77} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.2/asm-5.0.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.2
cp %{SOURCE78} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.2/asm-5.0.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.3
cp %{SOURCE79} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.3
cp %{SOURCE80} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.0_BETA
cp %{SOURCE81} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.0_BETA/asm-6.0_BETA.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.0_BETA
cp %{SOURCE82} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.0_BETA/asm-6.0_BETA.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.1.1
cp %{SOURCE83} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.1.1/asm-6.1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.2
cp %{SOURCE84} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.2/asm-6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.2
cp %{SOURCE85} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/6.2/asm-6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/7.0-beta
cp %{SOURCE86} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/7.0-beta/asm-7.0-beta.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/7.0
cp %{SOURCE87} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/7.0/asm-7.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/7.0
cp %{SOURCE88} %{buildroot}/usr/share/java/.m2/repository/org/ow2/asm/asm/7.0/asm-7.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/asm/asm-commons/3.3.1/asm-commons-3.3.1.jar
/usr/share/java/.m2/repository/asm/asm-commons/3.3.1/asm-commons-3.3.1.pom
/usr/share/java/.m2/repository/asm/asm-parent/3.1/asm-parent-3.1.pom
/usr/share/java/.m2/repository/asm/asm-parent/3.3.1/asm-parent-3.3.1.pom
/usr/share/java/.m2/repository/asm/asm-tree/3.3.1/asm-tree-3.3.1.jar
/usr/share/java/.m2/repository/asm/asm-tree/3.3.1/asm-tree-3.3.1.pom
/usr/share/java/.m2/repository/asm/asm/3.1/asm-3.1.jar
/usr/share/java/.m2/repository/asm/asm/3.1/asm-3.1.pom
/usr/share/java/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar
/usr/share/java/.m2/repository/asm/asm/3.3.1/asm-3.3.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.1/asm-all-5.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-all/5.1/asm-all-5.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/4.1/asm-analysis-4.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/4.1/asm-analysis-4.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/6.2/asm-analysis-6.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/7.0-beta/asm-analysis-7.0-beta.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/7.0/asm-analysis-7.0.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-analysis/7.0/asm-analysis-7.0.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.2/asm-commons-5.0.2.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.2/asm-commons-5.0.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/7.0-beta/asm-commons-7.0-beta.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/6.0_ALPHA/asm-debug-all-6.0_ALPHA.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-debug-all/6.0_ALPHA/asm-debug-all-6.0_ALPHA.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/4.1/asm-parent-4.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/4.2/asm-parent-4.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.1/asm-parent-5.0.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.2/asm-parent-5.0.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.0.4/asm-parent-5.0.4.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/5.1/asm-parent-5.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/6.0_ALPHA/asm-parent-6.0_ALPHA.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-parent/6.0_BETA/asm-parent-6.0_BETA.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/4.1/asm-tree-4.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/4.1/asm-tree-4.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.0.2/asm-tree-5.0.2.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.0.2/asm-tree-5.0.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.1/asm-tree-5.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/5.1/asm-tree-5.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0-beta/asm-tree-7.0-beta.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/4.1/asm-util-4.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/4.1/asm-util-4.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.1/asm-util-5.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/5.1/asm-util-5.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/6.2/asm-util-6.2.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/6.2/asm-util-6.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/7.0-beta/asm-util-7.0-beta.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm-util/7.0-beta/asm-util-7.0-beta.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/4.1/asm-4.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/4.1/asm-4.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/4.2/asm-4.2.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/4.2/asm-4.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.2/asm-5.0.2.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.2/asm-5.0.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/5.1/asm-5.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/5.1/asm-5.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/6.0_BETA/asm-6.0_BETA.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/6.0_BETA/asm-6.0_BETA.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/6.1.1/asm-6.1.1.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/6.1.1/asm-6.1.1.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/6.2/asm-6.2.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/6.2/asm-6.2.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/7.0-beta/asm-7.0-beta.pom
/usr/share/java/.m2/repository/org/ow2/asm/asm/7.0/asm-7.0.jar
/usr/share/java/.m2/repository/org/ow2/asm/asm/7.0/asm-7.0.pom
